import { Platform, StyleSheet } from 'react-native';

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
  },
  android: { elevation: 3 },
  web: { boxShadow: '0 6px 18px rgba(15,23,42,0.08)' },
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
    alignItems: 'center',
  },
  scrollContentCompact: {
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  shell: {
    width: '100%',
    maxWidth: 720,
    gap: 16,
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    ...cardShadow,
  },
  panelCompact: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  formPanel: {
    width: '100%',
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 6,
  },
  fieldBlock: {
    marginBottom: 15,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'web' ? 11 : 4,
  },
  input: {
    flex: 1,
    minHeight: 32,
    padding: 0,
    fontSize: 15,
    color: '#0F172A',
  },
  textArea: {
    minHeight: 92,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 15,
    lineHeight: 21,
    color: '#0F172A',
    textAlignVertical: 'top',
  },
  templateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#DBEAFE',
    borderRadius: 14,
    backgroundColor: '#EFF6FF',
    padding: 12,
    marginBottom: 16,
  },
  templateIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DBEAFE',
  },
  templateText: {
    flex: 1,
  },
  templateTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    lineHeight: 20,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 12,
  },
  dateRowCompact: {
    flexDirection: 'column',
    gap: 0,
  },
  dateField: {
    flex: 1,
  },
  selectedProduct: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 12,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectedProductText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: '#166534',
  },
  resultList: {
    marginTop: 6,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  resultName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  resultTextBlock: {
    flex: 1,
  },
  resultMeta: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  emptyResult: {
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
  },
  emptyResultText: {
    fontSize: 12,
    color: '#64748B',
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: 10,
    marginTop: 2,
  },
  actionRowCompact: {
    flexDirection: 'column',
  },
  secondaryButton: {
    minHeight: 44,
    borderRadius: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    flexGrow: 1,
    flexBasis: 120,
  },
  fullWidthButton: {
    width: '100%',
    flexBasis: '100%',
  },
  buttonText: {
    fontSize: 13,
    fontWeight: '800',
  },
  printButtonWrap: {
    minHeight: 44,
    borderRadius: 14,
    overflow: 'hidden',
    flexGrow: 1,
    flexBasis: 220,
  },
  printButton: {
    minHeight: 44,
    borderRadius: 14,
    paddingHorizontal: 16,
    flex: 1,
  },
  printSelectButton: {
    minHeight: 44,
    borderRadius: 14,
    paddingHorizontal: 10,
  },
  printButtonText: {
    fontSize: 13,
    fontWeight: '800',
  },
  printFeedback: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  printFeedbackOk: {
    backgroundColor: '#F0FDF4',
    borderColor: '#BBF7D0',
  },
  printFeedbackError: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  printFeedbackText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
});

export default styles;
