import { Platform, StyleSheet } from 'react-native';

export const MENU_COLORS = {
  background: '#F7F9FC',
  surface: '#FFFFFF',
  surfaceAlt: '#F1F5F9',
  border: '#DDE5EF',
  borderStrong: '#B9C6D6',
  text: '#172033',
  muted: '#65758B',
  brand: '#E8F2FF',
  brandStrong: '#1D66D2',
  brandText: '#0E4EA8',
  good: '#E8F8EF',
  goodText: '#126C3A',
  warn: '#FFF5E6',
  warnText: '#945700',
  bad: '#FDECEC',
  badText: '#A32929',
  white: '#FFFFFF',
};

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: MENU_COLORS.background,
  },
  page: {
    flex: 1,
    backgroundColor: MENU_COLORS.background,
  },
  toolbar: {
    minHeight: 72,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  titleBlock: {
    minWidth: 0,
    flex: 1,
  },
  eyebrow: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  pageTitle: {
    color: MENU_COLORS.text,
    fontSize: 21,
    fontWeight: '800',
    marginTop: 3,
  },
  toolbarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  body: {
    flex: 1,
    flexDirection: 'row',
  },
  bodyCompact: {
    flexDirection: 'column',
  },
  sidebar: {
    width: 260,
    borderRightWidth: 1,
    borderRightColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 12,
  },
  sidebarCompact: {
    width: '100%',
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: MENU_COLORS.border,
    paddingVertical: 8,
  },
  menuList: {
    gap: 6,
  },
  menuListHorizontal: {
    flexDirection: 'row',
  },
  content: {
    flex: 1,
    minWidth: 0,
  },
  sectionTop: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionEyebrow: {
    color: MENU_COLORS.brandStrong,
    fontSize: 12,
    fontWeight: '800',
  },
  sectionTitle: {
    color: MENU_COLORS.text,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 2,
  },
  contentScroll: {
    flex: 1,
  },
  contentScrollBody: {
    paddingHorizontal: 18,
    paddingBottom: 28,
  },
  iconButton: {
    minHeight: 38,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    borderRadius: 8,
    backgroundColor: MENU_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButtonActive: {
    backgroundColor: MENU_COLORS.brand,
    borderColor: '#9BC4FF',
  },
  iconButtonDanger: {
    borderColor: '#F1B8B8',
  },
  iconButtonText: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '700',
  },
  iconButtonTextActive: {
    color: MENU_COLORS.brandText,
  },
  searchBox: {
    minWidth: 240,
    maxWidth: 420,
    flex: 1,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: MENU_COLORS.text,
    fontSize: 14,
    outlineStyle: 'none',
  },
  stack: {
    gap: 14,
  },
  dashboardStack: {
    gap: 14,
  },
  dashboardHero: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFD6F4',
    backgroundColor: '#F3F8FF',
    padding: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  dashboardHeroWarn: {
    borderColor: '#F1D08D',
    backgroundColor: '#FFF9EF',
  },
  dashboardHeroBad: {
    borderColor: '#E9A5A5',
    backgroundColor: '#FFF4F4',
  },
  costEngineHero: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFD6F4',
    backgroundColor: '#F5FAFF',
    padding: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  dashboardHeroMain: {
    flex: 2,
    minWidth: 320,
    gap: 10,
  },
  dashboardHeroSide: {
    flex: 1,
    minWidth: 280,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignContent: 'flex-start',
  },
  dashboardHeroTitle: {
    color: MENU_COLORS.text,
    fontSize: 26,
    fontWeight: '900',
  },
  dashboardHeroText: {
    color: MENU_COLORS.muted,
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 780,
  },
  quickActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  quickAction: {
    minWidth: 210,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  quickActionPrimary: {
    borderColor: MENU_COLORS.brandStrong,
    backgroundColor: MENU_COLORS.brandStrong,
  },
  quickActionIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: MENU_COLORS.brand,
  },
  quickActionText: {
    flex: 1,
    minWidth: 0,
  },
  quickActionTitle: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '900',
  },
  quickActionTitlePrimary: {
    color: MENU_COLORS.white,
  },
  quickActionSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  quickActionSubtitlePrimary: {
    color: '#DCEBFF',
  },
  countTile: {
    minWidth: 128,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  countValue: {
    color: MENU_COLORS.text,
    fontSize: 18,
    fontWeight: '900',
  },
  countLabel: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    minWidth: 170,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 16,
  },
  metricValue: {
    color: MENU_COLORS.text,
    fontSize: 24,
    fontWeight: '800',
  },
  metricValueGood: {
    color: MENU_COLORS.goodText,
  },
  metricValueWarn: {
    color: MENU_COLORS.warnText,
  },
  metricValueBad: {
    color: MENU_COLORS.badText,
  },
  metricLabel: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  metricHelper: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 6,
  },
  gridTwo: {
    flexDirection: 'row',
    gap: 14,
    flexWrap: 'wrap',
  },
  panel: {
    flex: 1,
    minWidth: 310,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 14,
  },
  panelIntro: {
    marginBottom: 10,
  },
  panelTitle: {
    color: MENU_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 3,
  },
  panelSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  panelNested: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
    marginTop: 14,
    gap: 8,
  },
  categorySummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categorySummaryCard: {
    minWidth: 190,
    flexGrow: 1,
    flexBasis: '30%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
  },
  categorySummaryTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  categorySummaryValue: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 5,
  },
  categorySummaryMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  operationalSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  costLogicNote: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFD6F4',
    backgroundColor: '#F5FAFF',
    padding: 12,
    marginTop: 12,
  },
  costLogicTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  costLogicText: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 5,
  },
  costEngineTimeline: {
    gap: 10,
  },
  costEngineStep: {
    flexDirection: 'row',
    gap: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
  },
  costEngineStepIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: MENU_COLORS.brand,
    flexShrink: 0,
  },
  costEngineStepText: {
    flex: 1,
    minWidth: 0,
  },
  costEngineStepTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  costEngineFormula: {
    color: MENU_COLORS.brandText,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 17,
    marginTop: 5,
  },
  costEngineDescription: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  nextRuleList: {
    gap: 9,
    marginTop: 12,
  },
  nextRuleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 11,
  },
  nextRuleText: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  channelRuleList: {
    gap: 12,
  },
  channelRuleCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
    gap: 12,
  },
  channelRuleHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  channelRuleTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  channelRuleTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  channelRuleSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  channelFieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  channelField: {
    minWidth: 128,
    flexBasis: '30%',
    flexGrow: 1,
  },
  roundingButton: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    paddingHorizontal: 10,
    paddingVertical: 11,
    justifyContent: 'center',
  },
  roundingButtonText: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  channelResultGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  activeCostPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#B8D6FF',
    backgroundColor: '#F5FAFF',
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  activeCostHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  familyPreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  familyPreviewCard: {
    minWidth: 260,
    flexBasis: '31%',
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
  },
  familyPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  splitLayout: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 14,
  },
  listPanel: {
    width: 390,
    maxWidth: '100%',
    flexShrink: 0,
    gap: 8,
  },
  resourceTablePanel: {
    width: 660,
    maxWidth: '100%',
    flexShrink: 0,
  },
  ingredientsTablePanel: {
    width: 940,
  },
  listGroup: {
    gap: 8,
  },
  listGroupTitle: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  menuCatalogToolbar: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  menuCatalogTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  menuCategoryCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    marginBottom: 8,
    overflow: 'hidden',
  },
  menuCategoryCardDragging: {
    borderColor: MENU_COLORS.brandStrong,
    backgroundColor: '#F5FAFF',
    opacity: 0.86,
  },
  menuCategoryCardChild: {
    borderLeftWidth: 3,
    borderLeftColor: '#BFD6F4',
  },
  menuCategoryHeader: {
    minHeight: 62,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuCategoryOrderBadge: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFD6F4',
    backgroundColor: MENU_COLORS.brand,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  menuCategoryOrderText: {
    color: MENU_COLORS.brandText,
    fontSize: 13,
    fontWeight: '900',
  },
  menuCategoryHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  menuCategoryTitleLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  menuCategoryTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  menuCategoryMeta: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  menuCategoryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
  },
  menuCategoryDragHandle: {
    width: 30,
    height: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'grab',
  },
  menuCategoryProducts: {
    borderTopWidth: 1,
    borderTopColor: MENU_COLORS.border,
    padding: 8,
    gap: 8,
    backgroundColor: '#FBFDFF',
  },
  menuCategoryDirectLabel: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    paddingHorizontal: 4,
    paddingTop: 2,
  },
  menuCategoryChildrenHint: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: 4,
    paddingVertical: 6,
  },
  rowCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowCardActive: {
    borderColor: MENU_COLORS.brandStrong,
    backgroundColor: '#F5FAFF',
  },
  rowContent: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  rowSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  rowMeta: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 16,
    marginTop: 6,
  },
  rowRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    maxWidth: 118,
  },
  rowMoney: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'right',
  },
  badgeLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 7,
  },
  badge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: MENU_COLORS.text,
  },
  toneNeutral: {
    backgroundColor: MENU_COLORS.surfaceAlt,
    borderColor: MENU_COLORS.border,
  },
  toneGood: {
    backgroundColor: MENU_COLORS.good,
    borderColor: '#BFE8CE',
  },
  toneWarn: {
    backgroundColor: MENU_COLORS.warn,
    borderColor: '#F5D69A',
  },
  toneBad: {
    backgroundColor: MENU_COLORS.bad,
    borderColor: '#F0B0B0',
  },
  detailPanel: {
    flex: 1,
    minWidth: 0,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 14,
    zIndex: 2,
    ...Platform.select({
      web: {
        position: 'sticky',
        top: 12,
        alignSelf: 'flex-start',
      },
      default: {},
    }),
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  detailHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  detailTitle: {
    color: MENU_COLORS.text,
    fontSize: 22,
    fontWeight: '800',
    marginTop: 8,
  },
  detailSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  detailActions: {
    flexDirection: 'row',
    gap: 8,
  },
  visualThumb: {
    width: 54,
    height: 54,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  visualThumbSmall: {
    width: 46,
    height: 46,
  },
  visualThumbLarge: {
    width: 112,
    height: 112,
  },
  visualImage: {
    width: '100%',
    height: '100%',
  },
  visualInitial: {
    color: MENU_COLORS.brandText,
    fontSize: 13,
    fontWeight: '900',
  },
  productHero: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  productHeroText: {
    flex: 1,
    minWidth: 0,
  },
  productHeroTitle: {
    color: MENU_COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  productHeroSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  detailTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: MENU_COLORS.border,
    paddingBottom: 10,
    marginBottom: 12,
  },
  detailTabButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  detailTabButtonActive: {
    backgroundColor: MENU_COLORS.brand,
    borderColor: '#9BC4FF',
  },
  detailTabText: {
    color: MENU_COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },
  detailTabTextActive: {
    color: MENU_COLORS.brandText,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoCell: {
    minWidth: 150,
    flexGrow: 1,
    flexBasis: '30%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 12,
  },
  infoLabel: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  infoValue: {
    color: MENU_COLORS.text,
    fontSize: 17,
    fontWeight: '800',
    marginTop: 5,
  },
  infoHelper: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 5,
  },
  nodeCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    padding: 10,
    marginTop: 8,
  },
  nodeCardChild: {
    backgroundColor: MENU_COLORS.surface,
  },
  nodeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  nodeTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  nodeTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  nodeMeta: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    marginTop: 3,
  },
  nodeCost: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'right',
  },
  nodeChildren: {
    marginTop: 8,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: MENU_COLORS.border,
  },
  componentCostGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: MENU_COLORS.border,
  },
  componentCostCell: {
    minWidth: 145,
    flexGrow: 1,
    flexBasis: '22%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 10,
  },
  compositionPiece: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: 10,
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
    marginTop: 8,
    backgroundColor: MENU_COLORS.surface,
  },
  compositionPieceErp: {
    borderColor: MENU_COLORS.borderStrong,
  },
  compositionPieceDraft: {
    borderColor: MENU_COLORS.warnText,
    backgroundColor: MENU_COLORS.warn,
  },
  compositionPieceIdentity: {
    minWidth: 170,
    flexGrow: 2,
    flexBasis: '24%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  compositionPieceIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    flexShrink: 0,
  },
  compositionPieceIconErp: {
    borderColor: MENU_COLORS.borderStrong,
    backgroundColor: MENU_COLORS.brand,
  },
  compositionPieceIconDraft: {
    borderColor: MENU_COLORS.warnText,
    backgroundColor: MENU_COLORS.surface,
  },
  compositionPieceBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginBottom: 5,
  },
  compositionPieceReference: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    marginTop: 3,
  },
  compositionPieceRole: {
    minWidth: 145,
    flexGrow: 1,
    flexBasis: 145,
    borderLeftWidth: 1,
    borderLeftColor: MENU_COLORS.border,
    paddingLeft: 10,
    justifyContent: 'center',
  },
  compositionPieceCode: {
    minWidth: 105,
    flexGrow: 0,
    flexBasis: 105,
    borderLeftWidth: 1,
    borderLeftColor: MENU_COLORS.border,
    paddingLeft: 10,
    justifyContent: 'center',
  },
  compositionPieceCodeValue: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 4,
  },
  compositionPieceMissing: {
    color: MENU_COLORS.badText,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 4,
  },
  compositionPieceCost: {
    minWidth: 130,
    flexGrow: 1,
    flexBasis: 150,
    borderLeftWidth: 1,
    borderLeftColor: MENU_COLORS.border,
    paddingLeft: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  compositionPieceQuantity: {
    minWidth: 112,
    flexGrow: 0,
    flexBasis: 112,
    borderLeftWidth: 1,
    borderLeftColor: MENU_COLORS.border,
    paddingLeft: 10,
    justifyContent: 'center',
  },
  compositionPieceResult: {
    minWidth: 110,
    flexGrow: 1,
    flexBasis: '18%',
    borderLeftWidth: 1,
    borderLeftColor: MENU_COLORS.border,
    paddingLeft: 10,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  compositionPieceValue: {
    color: MENU_COLORS.text,
    fontSize: 15,
    fontWeight: '900',
    marginTop: 4,
  },
  compositionPieceCalculation: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    marginTop: 3,
    marginBottom: 5,
  },
  compositionPieceResultValue: {
    color: MENU_COLORS.text,
    fontSize: 17,
    fontWeight: '900',
    marginTop: 4,
    textAlign: 'right',
  },
  compositionPieceFormula: {
    color: MENU_COLORS.muted,
    fontSize: 11,
    marginTop: 3,
    textAlign: 'right',
  },
  addonGroupCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#C8DBF4',
    padding: 12,
    backgroundColor: '#F3F8FF',
    gap: 10,
  },
  addonGroupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#D8E8FA',
  },
  addonGroupTitle: {
    color: MENU_COLORS.text,
    fontSize: 15,
    fontWeight: '900',
  },
  addonGroupMeta: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    marginTop: 3,
  },
  addonOptionCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D8E8FA',
    padding: 10,
    backgroundColor: MENU_COLORS.surface,
  },
  preparationSuggestionBlock: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F1D08D',
    backgroundColor: '#FFF9EF',
    padding: 12,
    marginTop: 10,
    gap: 9,
  },
  localDraftSection: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F1D08D',
    backgroundColor: '#FFF9EF',
    padding: 12,
    marginTop: 10,
    marginBottom: 10,
    gap: 9,
  },
  localDraftHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  localDraftIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF1D6',
    flexShrink: 0,
  },
  localDraftTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  localDraftDescription: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  localDraftRelationCard: {
    borderTopWidth: 1,
    borderTopColor: '#F1D08D',
    paddingTop: 9,
    gap: 8,
  },
  localDraftRelationMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  localDraftTypeIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#F1D08D',
    backgroundColor: MENU_COLORS.surface,
    flexShrink: 0,
  },
  localDraftQuantityBox: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F1D08D',
    backgroundColor: MENU_COLORS.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  localDraftQuantityValue: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 3,
  },
  preparationSuggestionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  preparationSuggestionTitle: {
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },
  preparationSuggestionText: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  preparationSuggestionRow: {
    borderTopWidth: 1,
    borderTopColor: '#F1D08D',
    paddingTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  recipeComponentBlock: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 10,
    gap: 8,
  },
  recipeComponentAudit: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  emptyState: {
    minHeight: 120,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    gap: 8,
  },
  emptyStateText: {
    color: MENU_COLORS.muted,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: MENU_COLORS.surfaceAlt,
    borderBottomWidth: 1,
    borderBottomColor: MENU_COLORS.border,
  },
  tableHeaderText: {
    width: 180,
    color: MENU_COLORS.text,
    fontSize: 12,
    fontWeight: '800',
    padding: 10,
  },
  tableHeaderTextWide: {
    width: 260,
  },
  tableHeaderTextNarrow: {
    width: 120,
  },
  tableHeaderTextCompactName: {
    width: 190,
  },
  tableHeaderTextCompactUnit: {
    width: 62,
  },
  tableHeaderTextCompactCost: {
    width: 144,
  },
  tableHeaderTextCompactBase: {
    width: 116,
  },
  tableHeaderTextCompactOrigin: {
    width: 146,
  },
  tableHeaderTextCompactAudit: {
    width: 104,
  },
  tableHeaderTextCompactLink: {
    width: 154,
  },
  tableGroupHeader: {
    width: '100%',
    backgroundColor: '#EAF4FF',
    borderBottomWidth: 1,
    borderBottomColor: '#BFDBFE',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  tableGroupTitle: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '900',
  },
  tableGroupSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    marginTop: 2,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    borderLeftWidth: 4,
    borderLeftColor: 'transparent',
  },
  tableRowGood: {
    backgroundColor: '#F0FDF4',
    borderLeftColor: '#10b981',
  },
  tableRowWarn: {
    backgroundColor: '#FFFBEB',
    borderLeftColor: '#e67e22',
  },
  tableRowBad: {
    backgroundColor: '#FEF2F2',
    borderLeftColor: '#c10015',
  },
  tableRowActive: {
    backgroundColor: '#EAF4FF',
    borderLeftColor: MENU_COLORS.brandStrong,
    ...Platform.select({
      web: {
        boxShadow: 'inset 0 0 0 1px #9BC4FF',
      },
      default: {},
    }),
  },
  tableCell: {
    width: 180,
    color: MENU_COLORS.text,
    fontSize: 12,
    lineHeight: 17,
    padding: 10,
  },
  tableCellWide: {
    width: 260,
  },
  tableCellNarrow: {
    width: 120,
  },
  tableCellCompactUnit: {
    width: 62,
  },
  tableCellCompactCost: {
    width: 144,
  },
  tableCellCompactBase: {
    width: 116,
  },
  tableCellCompactOrigin: {
    width: 146,
  },
  tableCellCompactAudit: {
    width: 104,
  },
  tableCellCompactLink: {
    width: 154,
  },
  tableIdentity: {
    width: 260,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tableIdentityCompact: {
    width: 190,
  },
  tableIdentityText: {
    flex: 1,
    minWidth: 0,
  },
  tableCellText: {
    color: MENU_COLORS.text,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  tableEditableCost: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tableInput: {
    minWidth: 86,
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9BC4FF',
    backgroundColor: '#EFF6FF',
    color: MENU_COLORS.text,
    fontSize: 12,
    fontWeight: '800',
    paddingHorizontal: 8,
    outlineStyle: 'none',
  },
  sourceChoiceCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 10,
    gap: 8,
  },
  sourceChoiceCardActive: {
    borderColor: '#9BC4FF',
    backgroundColor: '#F5FAFF',
  },
  sourceChoiceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  sourceChoiceActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sourceLinkButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignSelf: 'flex-start',
  },
  evidenceLinkGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  sourceLinkText: {
    color: MENU_COLORS.brandText,
    fontSize: 12,
    fontWeight: '800',
  },
  costSummaryHero: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#B8D6FF',
    backgroundColor: '#F5FAFF',
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  costSummaryValue: {
    color: MENU_COLORS.text,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  costSummaryMeta: {
    flex: 1,
    minWidth: 180,
    alignItems: 'flex-end',
  },
  sourceDecisionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  processTable: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    overflow: 'hidden',
  },
  activeCostTable: {
    minWidth: 1080,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    overflow: 'hidden',
    marginTop: 12,
  },
  ingredientsCostTable: {
    minWidth: 770,
  },
  quantityField: {
    minWidth: 120,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9BC4FF',
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quantityFieldCompact: {
    minWidth: 104,
    flexShrink: 0,
  },
  quantityInput: {
    flex: 1,
    minWidth: 42,
    color: MENU_COLORS.text,
    fontSize: 14,
    fontWeight: '800',
    outlineStyle: 'none',
  },
  quantityUnit: {
    color: MENU_COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  costControlPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surface,
    padding: 10,
    gap: 10,
  },
  costModeList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  costModeButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    backgroundColor: MENU_COLORS.surfaceAlt,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  costModeButtonActive: {
    borderColor: '#9BC4FF',
    backgroundColor: MENU_COLORS.brand,
  },
  costModeText: {
    color: MENU_COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },
  costModeTextActive: {
    color: MENU_COLORS.brandText,
  },
  costManualRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  primaryButton: {
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: MENU_COLORS.brandStrong,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginTop: 14,
  },
  primaryButtonText: {
    color: MENU_COLORS.white,
    fontSize: 13,
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButtonText: {
    color: MENU_COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalCard: {
    width: '100%',
    maxWidth: 760,
    maxHeight: '92%',
    borderRadius: 8,
    backgroundColor: MENU_COLORS.surface,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    overflow: 'hidden',
  },
  modalHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: MENU_COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: {
    color: MENU_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  modalSubtitle: {
    color: MENU_COLORS.muted,
    fontSize: 13,
    marginTop: 3,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MENU_COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    padding: 16,
  },
  modalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  modalField: {
    flexGrow: 1,
    flexBasis: '45%',
    minWidth: 220,
  },
  modalFieldWide: {
    flexBasis: '100%',
  },
  modalLabel: {
    color: MENU_COLORS.text,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  modalInput: {
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#B8D6FF',
    backgroundColor: '#F5FAFF',
    color: MENU_COLORS.text,
    fontSize: 14,
    paddingHorizontal: 10,
    outlineStyle: 'none',
  },
  modalTextarea: {
    minHeight: 92,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  modalFooter: {
    borderTopWidth: 1,
    borderTopColor: MENU_COLORS.border,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
});
